mpt/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from rest_framework import routers

from . import views


router = routers.SimpleRouter(trailing_slash=False)

app_name = 'mpt'


router.register(r'mpt_profile', views.MptProfileViewSet, base_name='mpt_profile')
router.register(r'assistance', views.AssistanceViewSet, base_name='assistance')
router.register(r'mentor_student', views.MentorStudentViewSet, base_name='mentor_student')
router.register(r'company', views.CompanyViewSet, base_name='company')
router.register(r'vacancy', views.VacancyViewSet, base_name='vacancy')
router.register(r'skills_option', views.SkillsOptionViewSet, base_name='skills_option')
router.register(r'knowledge_option', views.KnowledgeOptionViewSet, base_name='mpt_profile')
router.register(r'vacancy_favorite', views.VacancyFavoriteViewSet, base_name='vacancy_favorite')


urlpatterns = [
    # include new baquara URLs before baquaras
    url(r'^', include('courses_frontend.urls')),

    # include baquara URLs
    url(r'^', include('config.urls')),

    # customized apis
    url(r'^api/', include(router.urls)),

    # Enhance profiles
    url(r'^complete-profile.template.html', TemplateView.as_view(template_name='components/profile/complete-profile.html'), name='complete-profile'),

    # Job openings
    url(r'^opening-candidates.template.html', TemplateView.as_view(template_name='components/openings/opening-candidates.html'), name='opening-candidates'),
    url(r'^opening-card.template.html', TemplateView.as_view(template_name='components/openings/opening-card.html'), name='opening-card'),
    url(r'^opening-detail.template.html', TemplateView.as_view(template_name='components/openings/opening-detail.html'), name='opening-detail'),
    url(r'^opening-edit.template.html', TemplateView.as_view(template_name='components/openings/opening-edit.html'), name='opening-edit'),
    url(r'^openings-list.template.html', TemplateView.as_view(template_name='components/openings/openings-list.html'), name='openings-list'),

    # Mentorship
    url(r'^mentorships-list.template.html', TemplateView.as_view(template_name='components/mentorship/mentorships-list.html'), name='mentorships-list'),
]

mpt/forms.py
from allauth.account.forms import SignupForm
from django import forms
from baquara.users.models import User, GenderOption, SexualOrientationOption, RaceOption
from django.utils.translation import gettext_lazy as _
from cities_light.models import City

class DateInput(forms.DateInput):
    input_type = 'date'

class CustomSignupForm(SignupForm):
    preferred_language = forms.ChoiceField(choices=User.LANGUAGES_CHOICES)
    accepted_terms = forms.BooleanField(initial=False, required=False)
    birth_date = forms.DateField( required=True, widget=DateInput(
        attrs={
            'title' : _('Birth Date'),
            'class':'form-control',
        }
    ))
    name = forms.CharField(max_length=128)
    gender = forms.ModelChoiceField(queryset = GenderOption.objects.all(),empty_label=_("Select your gender"), widget=forms.Select(
        attrs={
            'class':'form-control',
        }
    ) )
    city = forms.ModelChoiceField(queryset = City.objects.all(),empty_label=_("Inform your town of residence"), widget=forms.Select(
        attrs={
            'class':'form-control',
        }
    ) )
    race = forms.ModelChoiceField(queryset = RaceOption.objects.all(), empty_label=_("Tell us how you identify yourself"), widget=forms.Select(
        attrs={
            'class':'form-control',
        }
    ) )
    institution = forms.CharField(max_length=128)
    phone_number = forms.CharField(max_length=128)
    cpf =  forms.CharField(max_length=128)


    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.gender = self.cleaned_data['gender']
        user.race = self.cleaned_data['race']
        user.birth_date = self.cleaned_data['birth_date']
        user.city = self.cleaned_data['city']
        user.preferred_language = self.cleaned_data['preferred_language']
        user.accepted_terms = self.cleaned_data['accepted_terms']
        user.name = self.cleaned_data['name']
        user.institution = self.cleaned_data['institution']
        user.phone_number = self.cleaned_data['phone_number']
        user.cpf = self.cleaned_data['cpf']
        user.save()

        return user

mpt/templates/administration/_alert.html
{% load i18n %}
<!-- ALERT -->
<div class="tt-popup notifications" alert-popup ng-class="{'hidden': alert.hidden}">
    <div class="alert" ng-class="'alert-' + alert.type">
        <span class="message" ng-bind="alert.title">Error!</span>
        <button type="button" class="close" ng-click="alert.hidden=true"><i class="fa fa-times"></i></button>
    </div>
</div>
<!-- ALERT -->

mpt/templates/administration/course-certificate-template.html
{% extends "base.html" %}
{% load compress %}
{% load static %}
{% load i18n %}

{% block js %}
    {{ block.super }}

    <script src="https://unpkg.com/angular-sortable-view@0.0.17/src/angular-sortable-view.min.js"></script>
    <script src="https://unpkg.com/checklist-model@1.0.0/checklist-model.js"></script>

    {% compress js %}
    <!-- Core -->
    <script type="text/javascript" src="{% static 'js/core/app.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/core/controllers.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/core/services.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/core/filters.js' %}" charset="utf-8"></script>

    <script type="text/javascript" src="{% static 'js/directives/fixedBar.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/directives/alertPopup.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/directives/markdowneditor.js' %}" charset="utf-8"></script>

    <!-- Certificate -->
    <script type="text/javascript" src="{% static 'js/certificate/app.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/certificate/controllers.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/certificate/filters.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/certificate/services.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/directives/file.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/directives/previewImage.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/factories/timtec-models.js' %}" charset="utf-8"></script>
    {% endcompress %}

{% endblock %}

{% block wrapper_classes %}
wrapper-course-lesson
{% endblock %}

{% block body_attrs %}
ng-app="certification"
{% endblock %}

{% block content %}
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        function onFileSelected(event) {
            var selectedFile = event.target.files[0];
            var reader = new FileReader();
            var imgtag = document.getElementById(event.target.id + "-preview");

            reader.onload = function(event) {
                imgtag.src = event.target.result;
            };

            reader.readAsDataURL(selectedFile);
        }

        function onImgNotFound(event) {
            $(this).attr('src', '{% static "img/avatar-default.png" %}')
        }

        $("#base-logo, #site-logo, #cert-logo, #signature").change(onFileSelected);

        $("#profile-avatar").error(onImgNotFound);
    });
</script>
<section class="course certificate" ng-controller="CertificateTemplateCtrl" ng-cloack>

  {% include "_admin_header_inline.html" with course=course hide_editable_fields=True %}

  <!-- ACTIONS -->
  <div class="actions-menu" fixed-bar>
    <div class="container-fluid">
      {% include 'administration/_alert.html' %}
      <a href="{% url 'courses_legacy:course.certificate-templates' course.id %}" class="btn btn-danger cancel" translate>Back to templates list</a>
      <div class="actions-buttons pull-right">
        <button class="btn btn-primary btn-inverse delete" ng-click="deleteTemplate()" translate>Delete</button>
        {% verbatim %}
        <button class="btn btn-info" ng-class="{ 'edit' :  preview, 'preview' : !preview }" ng-click="preview = !preview">
          <span ng-if="preview" translate>Edit</span>
          <span ng-if="!preview" translate>View</span>
        </button>
        {% endverbatim %}
        <button class="btn btn-primary btn-inverse save" ng-click="saveTemplate()" translate>Save</button>
      </div>
    </div>
  </div>
  <!-- END ACTIONS -->

  <section class="page container-fluid">
  <!-- HEADER -->
  {% verbatim %}
  <header class="page-header">
    <h3 class="header-bottom-distance">
      <span ng-if="ct.document_type == 'receipt'" translate>Configure template for receipts</span>
      <span ng-if="ct.document_type == 'certificate'" translate>Configure template for certificates</span>
    </h3>
    <p class="lead"><span translate>Course</span>: {{ ct.course_name }}</p>
    <div class="help-text"><i class="fa fa-caret-down" aria-hidden="true"></i>
      <span translate>Edit template name (the final user won't see this name)</span>
    </div>
    <div class="editable-title"><input type="text" ng-model="ct.name" placeholder="{{'Template name' | translate}}"></div>
  </header>

  <div class="alert alert-info" role="alert" ng-class="{hide: !help}">
    <ul>
      <li translate>
        Never forget to Save any changes you make. Before saving it is possible and recommended to preview the changes made.
      </li>
      <li class="certificate-help">
        <span translate>
          To edit the template text, use the editor below and its features. In the text, you can place the following indicators, which will be replaced according to the description:
        </span>
        <ul>
          <li translate>{MODULE}: Certificate module name</li>
          <li translate>{CONTRACT}: Contract name</li>
          <li translate>{NUM_UNITS}: Number of units in the module</li>
          <li translate>{TURMA}: Turma na qual foi concluído o módulo</li>
        </ul>
      </li>
      <li translate>
        To delete an image from the template, just double-click it
      </li>
      <li translate>
        When you click cancel, you will be returned to the certificate listing page. Always remember to Save any changes you have made and want to keep
      </li>
      <li ng-if="message" ng-bind-html="message"></li>
    </ul>
  </div>
  {% endverbatim %}
  <!-- END HEADER -->

  <div class="certificate-content">
      {% verbatim %}
      <div class="edit-certificates" ng-hide="preview">
        <div class="certificate-container certificate-admin" ng-class="{'receipt-admin receipt' : ct.document_type == 'receipt'}">
          <div class="certificate-header">
            <div>
              <div class="certificate-title" ng-if="ct.document_type == 'receipt'" translate>Receipt</div>
              <div class="certificate-title" ng-if="ct.document_type == 'certificate'" translate>Certificate</div>
            </div>
          </div>
          <div class="certificate-info">
            <div class="certificate-template">
              <textarea ui-tinymce="tinymceOptions" class="editable-text" rows="1" ng-model="ct.organization_name" required></textarea>
            </div>
            <p class="student" translate>User name here</p>
            <p>concluiu a formação</p>
            <div class="certificate-course-name">{{ ct.course_name }}</div>
            <div class="certificate-template">
              <textarea ui-tinymce="tinymceOptions" class="editable-text" rows="3" ng-model="ct.text" required></textarea>
            </div>
          </div>
          <footer>
              <div class="certificate-signatures">
                <div class="coordinator-section">
                  <div class="certificate-signature">
                      <img alt=""
                          ng-dblclick="reset($event, 'signature')"
                          preview-image
                          ng-model="images.signature"
                          ng-src="{{ ct.signature_url }}"
                          class="img-responsive" />
                      <file id="signature" ng-model="images.signature" name="logo"></file>
                  </div>
                </div>
                <div class="coordinator-section">
                  <div class="certificate-signature">
                      <img alt=""
                          ng-dblclick="reset($event, 'second_signature')"
                          preview-image
                          ng-model="images.second_signature"
                          ng-src="{{ ct.second_signature_url }}"
                          class="img-responsive" />
                      <file id="second-signature" ng-model="images.second_signature" name="logo"></file>
                  </div>
                </div>
              </div>
          </footer>
        </div>
      </div>

      <div class="certificate-container" ng-class="{'receipt' : ct.document_type == 'receipt'}" ng-hide="!preview">
        <div class="certificate-header">
          <div>
            <div class="certificate-title" ng-if="ct.document_type == 'receipt'" translate>Receipt</div>
            <div class="certificate-title" ng-if="ct.document_type == 'certificate'" translate>Certificate</div>
          </div>
        </div>
        <div class="certificate-info">
          <span ng-bind-html="ct.organization_name"></span>
          <p class="student" translate>Person Name</p>
          <p>concluiu a formação</p>
          <div class="certificate-course-name">{{ ct.course_name }}</div>
          <span ng-bind-html="ct.text"></span>
        </div>
        <footer>
            <div class="certificate-signatures">
              <div class="coordinator-section">
                <div class="certificate-signature">
                    <img class="signature-preview" alt="" ng-src="{{ ct.signature_url }}">
                </div>
              </div>
              <div class="coordinator-section">
                <div class="certificate-signature">
                    <img class="signature-preview" alt="" ng-src="{{ ct.second_signature_url }}">
                </div>
              </div>
            </div>
        </footer>
      </div>
      {% endverbatim %}
  </div>
</section>
{% endblock %}

mpt/templates/administration/course-material-admin.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% block js %}
{{ block.super }}
<script src="https://unpkg.com/angular-gettext@2.4.2/dist/angular-gettext.min.js"></script>
<script src="https://unpkg.com/tinymce@4.5.10/tinymce.min.js"></script>
<script src="https://unpkg.com/ng-file-upload@12.0.4/dist/ng-file-upload.min.js"></script>
<script src="https://unpkg.com/angular-ui-tinymce@0.0.19/dist/tinymce.min.js"></script>
<script src="https://unpkg.com/dropzone@3.12.0/lib/dropzone.js"></script>

<script src="{% static 'js/mpt.ui.tinymce.courses-legacy.config.js' %}"></script>

{% compress js %}
<script type="text/javascript" src="{% static 'js/course_material/app.js' %}"></script>
<script type="text/javascript" src="{% static 'js/course_material/controllers.js' %}"></script>
<script type="text/javascript" src="{% static 'js/course_material/services.js' %}"></script>
<script type="text/javascript" src="{% static 'js/course_material/filters.js' %}"></script>
<script type="text/javascript" src="{% static 'js/directives/alertPopup.js' %}"></script>
{% endcompress %}

{% endblock %}
{% block body_attrs %}
ng-app="courseMaterial"
{% endblock %}
{% block wrapper_classes %}
wrapper-course-lesson
{% endblock %}
{% block content %}
<script>
    window.course_id = {{ course.pk }};
</script>

<!-- CONTAINER -->
<div class="course course-material" ng-app="courseMaterial">

    <!-- ACTIONS -->
    <div class="actions-menu actions-menu-message" ng-hide="alert.hidden" fixed-bar>
        <div class="container">
            <div class="actions-buttons"></div>
            {% include 'administration/_alert.html' %}
        </div>
    </div>
    <!-- END ACTIONS -->

    {% include "_admin_header_inline.html" with course=course hide_editable_fields=True %}

    <!-- MAIN CONTENT -->
    <section class="course-content page container-fluid" ng-controller="CourseMaterialEditorCtrl">

        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <header class="page-header">
                    <h3 translate>Additional Materials</h3>
                </header>

                <div ng-hide="course_materials.$resolved">
                    <i class="loading fa fa-refresh fa-spin"></i>
                </div>

                <!-- Explicação inicial sobre material de curso -->
                <div class="add-content">
                    <div class="language-selection-container"><b class="page-subtitle" translate>Select the language for the materials</b></div>
                    <button class="btn btn-primary" ng-class="editingCourseLanguage === 'en' ? 'active-language': ''"
                        ng-click="setLanguage('en')">EN</button>
                    <button class="btn btn-primary" ng-class="editingCourseLanguage === 'pt-br' || editingCourseLanguage === 'pt_br' ? 'active-language': ''"
                        ng-click="setLanguage('pt-br')">PT-BR</button>
                    <button class="btn btn-primary" ng-class="editingCourseLanguage === 'es' ? 'active-language': ''"
                        ng-click="setLanguage('es')">ES</button>
                </div>

                <!-- /Explicação inicial sobre material de curso -->
                <b class="page-subtitle">
                    <span translate>Text that students will see in the area of additional materials</span>
                    <button class="btn btn-sm btn-primary edit desc-material pull-right"
                        ng-show="course_material.text && !course_material.editing"
                        ng-click="course_material.editing=true" translate>Edit</button>
                </b>

                <!-- Botões para a lógica de visualização do campo de texto -->

                <div class="materials-text">
                    <!-- Visualização do material de curso -->
                    <div class="materials-message" ng-show="course_material.text && !course_material.editing"
                        ng-bind-html="get_as_safe_html(course_material.text)"></div>
                    <!-- /Visualização do material de curso -->
                </div>
                <!-- Edição do material do curso -->
                <form name="new_material_text" class="new-thread" novalidate
                    ng-submit="course_material.text; new_material_text.$valid && save_course_material()"
                    ng-init="course_material.text" ng-show="!course_material.text || course_material.editing">
                    <div class="form-group">
                        <textarea ui-tinymce="tinymceOptions" ng-model="course_material.text"
                            name="text" ng-hide="!course_materials.$resolved" required></textarea>
                    </div>
                    <div class="form-group edit_material">
                        <button type="button" value="cancelar" class="btn btn-sm btn-danger delete" ng-click="course_material.editing=false;" translate>Cancel</button>
                        <button type="submit" value="salvar" class="btn btn-sm btn-primary save pull-right" translate>Save</button>
                    </div>
                </form>
            <!-- /Edição do material do curso -->

            <b class="page-subtitle" translate>
                Files upload
            </b>
            <!-- ASIDE -->
                <div >
                    <form action="{% url 'courses_legacy:file_upload' course.slug  %}"
                        class="col-xs-6 col-sm-4 col-md-4 col-lg-4 dropzone textcenter"
                        id="file-dropzone">
                        <p translate>Drop files to upload (or click)</p>
                        {% csrf_token %}
                        {% verbatim %}
                        <input type="hidden" name="course_material" value="{{ course_material.id }}" id="id_course_material">
                        {% endverbatim %}
                    </form>
                </div>
            </div>
            <div class="col-xs-10 col-sm-8 col-md-8">
                <p ng-show="files_course.length==0" translate>No files in course material</p>
                <ul class="uploaded-files-list" ng-show="files_course.length>0">
                    <li>
                        <b class="page-subtitle" translate>Materials</b>
                    </li>
                    <li ng-repeat="file_obj in files_course">
                        {% verbatim %}
                        <a ng-href="{{ file_obj.file }}" ng-if="!check_editing || check_editing !== file_obj.id" target="_blank" class="file_name">{{ file_obj.title }}</a>
                        <div class="editable-text" ng-if="check_editing && check_editing === file_obj.id">
                            <input type="text" ng-model="file_name" id="id_name" placeholder="Insert a name for the file">
                        </div>
                        <div class="edit-material">
                            <button ng-if="check_editing && check_editing === file_obj.id" class="btn btn-cancel" ng-click="edit_cancel()" translate>Cancel</button>
                            <button ng-if="check_editing && check_editing === file_obj.id" class="btn btn-success" ng-click="save_edit(file_obj); show_success_message=true" translate>Save</button>
                        </div>

                        <div class="file-link">
                            <p ng-href="{{ file_obj.file }}" target="_blank">{{file_obj.file|filename}}</p>
                            <div class="file-edit pull-right">
                                <button type="submit" target="_blank" class="btn btn-xs" ng-click="edit_file(file_obj)"><i class="fa fa-edit"></i><span class="sr-only" translate>edit material</span></button>
                                <button type="submit" target="_blank" ng-click="delete_file(file_obj)" class="btn btn-xs btn-warning"><i class="fa fa-times" aria-hidden="true"></i><span class="sr-only" translate>delete material</span></button>
                            </div>

                        </div>
                        {% endverbatim %}
                        <br/>
                    </li>
                </ul>
            </div>
            <!-- END ASIDE -->
        </div>
        </div>
        <!-- END ROW -->
    </section>
    <!-- END MAIN CONTENT-->
</div>
<!-- END CONTAINER -->
<script type="text/javascript">
    $(document).ready( function(){
        $('#course-material-text a').attr('target', '_blank');
    });
</script>

<script type="text/javascript">
    Dropzone.autoDiscover = false;
    $('.dropzone').dropzone({
        init: function() {
            var that = this;
            that.on('success', function(file) {
                window.location.reload();
            });
        }
    });
</script>
{% endblock %}